---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "development/Dockerfile"
x-nautobot-base: &nautobot-base
  image: "nautobot-golden-config/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  env_file:
    - "dev.env"
  tty: true

version: "3.4"
services:
  nautobot:
    command: "nautobot-server runserver 0.0.0.0:8080 --insecure"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "redis"
    <<: *nautobot-build
    <<: *nautobot-base
  celery:
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
    healthcheck:
      disable: true
    depends_on:
      - "nautobot"
    entrypoint: "nautobot-server celery worker -B -l INFO"
    <<: *nautobot-base
  db:
    image: "postgres:14"
    command: postgres -c 'max_connections=2000'
    env_file:
      - "dev.env"
    volumes:
      - "pgdata_nautobot_golden_config:/var/lib/postgresql/data"
  redis:
    image: "redis:7-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
volumes:
  pgdata_nautobot_golden_config:  # yamllint disable-line rule:empty-values
