---
stages:
  - name: "lint"
  - name: "test"
  - name: "verify_pypi_release"
    if: "tag IS present"  
  - name: "deploy-github"
    if: "tag IS present"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"
python:
  - 3.6
  - 3.7
  - 3.8

services:
  - "docker"

# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_install:
  - 'docker login -u "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"'  # yamllint disable-line rule:quoted-strings
before_script:
  - "pip install invoke toml docker-compose poetry"
script:
  - "invoke build --python-ver $TRAVIS_PYTHON_VERSION"
  - "invoke unittest"

jobs:
  include:
    - stage: "lint"
      before_script:
        - "pip install invoke toml docker-compose"
        - "invoke build"
      script:
        - "invoke black"
        - "invoke bandit"
        - "invoke pydocstyle"
        - "invoke pylint"

    - stage: "verify_pypi_release"
      before_script:
        - "pip install --upgrade pip"
        - "pip install invoke poetry toml"
        - "poetry config virtualenvs.create false"
        - "poetry install --no-interaction"
      script:
        - "invoke check-pypi-version"

    - stage: "deploy-github"
      before_script:
        - "pip install --upgrade pip"
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry build"
      deploy:
        provider: "releases"
        api_key: "$GITHUB_AUTH_TOKEN"
        file_glob: true
        file: "dist/*"
        skip_cleanup: true
        "on":
          all_branches: true

    - stage: "deploy_pypi"
      before_script:
        - "pip install --upgrade pip"
        - "pip install poetry"
      script:
        - "echo Deploying the release to PyPI"
        - "poetry version $TRAVIS_TAG"
      deploy:
        provider: "script"
        skip_cleanup: true
        script: "poetry publish --build -u __token__ -p $PYPI_TOKEN"
        "on":
          all_branches: true
